theme: jekyll-theme-slate
title: Marcelle Lee
author:
  name: Marcelle Lee
  email : marcelle at marcellelee.com
  github : marcellelee
  twitter : marcellelee
  feedburner : nil
description: Cybersecurity Resources
exclude: ["README.md", "Rakefile", "LICENSE.md"]

JB :
  version : 0.3.0
  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil
  comments :
    provider : false
  analytics :
    provider : false
  sharing :
     provider : false
